### ISSUE TITLE
Can't set wifi credentials through BLE

### ISSUE THREAD

**Issue by ChristopherMillon** [mongoose-os-libs/bt-common#18]
![image](https://user-images.githubusercontent.com/11379698/76129164-7b1c3700-5ffe-11ea-8f4e-7ce5f2aa587d.png)

As you can see, there isn't 3 attributes to which I can write in order to change the configuration, as described here https://mongoose-os.com/blog/bluetooth-support-for-esp32/

**Comment by rojer** [comment]
on your screenshot you have the debug service (https://github.com/mongoose-os-libs/bt-service-debug) and the RPC service (https://github.com/mongoose-os-libs/rpc-gatts)

you need service 5f6d4f53-5f43-**4647**-5f53-56435f49445f, provided by  https://github.com/mongoose-os-libs/bt-service-config.
make sure you have that library in your firmware.

i know the UUIDs are not very readable, you need to squint a bit to distinguish them :)

**Comment by ChristopherMillon** [comment]
@rojer thank you for your answer, it helped me make some of progress!
Now I'm unsure how to make it work, I added the lib like so:

```
author: mongoose-os
description: A JS-enabled demo Mongoose OS firmware
# arch: PLATFORM
version: 1.0
manifest_version: 2017-05-18
libs_version: ${mos.version}
modules_version: ${mos.version}
mongoose_os_version: ${mos.version}

config_schema:
  - ["mqtt.server", "iot.eclipse.org:1883"]
  - ["i2c.enable", true]

tags:
  - js

filesystem:
  - fs

libs:
  - origin: https://github.com/mongoose-os-libs/boards
  - origin: https://github.com/mongoose-os-libs/js-demo-bundle
  - origin: https://github.com/mongoose-os-libs/bt-service-config
```

But the configuration attribute is still not showing
